db.url=jdbc:postgresql://db.pbsfdmrmbqvskuaqxaau.supabase.co:5432/postgres?sslmode=require
db.host=db.pbsfdmrmbqvskuaqxaau.supabase.co
db.port=5432
db.database=postgres
db.user=postgres.pbsfdmrmbqvskuaqxaau
db.password=V8yU6isoaFmGhXp8